method: "None"  # Options: "canny", "sobel", "None"
loss: "distanceLength"  # Options: "distanceLength", "distance", "length"
undistort_method: "default"  # Options: "default", "rational", "thin_prism"
smooth_lambda: 0.2
filter_low_angle: 45
filter_high_angle: 135
binary_threshold: 240
canny_lower: 100
canny_upper: 150
initial_linear_speed: 0.3
initial_angular_speed: 0.0
max_angular_speed: 1.0
sobel_threshold: 50
hough_threshold: 30
hough_min_line_length: 60
hough_max_line_gap: 50
blur_image: true
easy_action: true
dilate_image: true
smooth_angle: true
horizon_center: true
undistort_image: true
enhance_vertical_edges: true
save_images: true 
debug: 2