detect_marker: true
detect_robot: false
show_contour_area: false 
save_robot_detection_images: true
initial_x_location: 0.0
initial_y_location: -4.0
target_x_location: 0.0
target_y_location: 4.0
notebook_display: true
debug: 10

use_custom_detector_parameters: true
detector_parameters:
  adaptiveThreshWinSizeMin: 3
  adaptiveThreshWinSizeMax: 15  # NO
  adaptiveThreshWinSizeStep: 4  # NO
  minMarkerPerimeterRate: 0.04  # NO 
  minMarkerPerimeterRate: 0.01  # NO
  maxMarkerPerimeterRate: 4.0
  polygonalApproxAccuracyRate: 0.02
  minMarkerDistanceRate: 0.5  # NO