detect_marker: true
detect_robot: true
show_contour_area: false 
save_robot_detection_images: true
initial_x_location: 0.0
initial_y_location: -4.0
target_x_location: 0.0
target_y_location: 4.0
notebook_display: true
debug: 3

use_custom_detector_parameters: true
detector_parameters:
  adaptiveThreshWinSizeMin: 3
  # adaptiveThreshWinSizeMax: 15
  # adaptiveThreshWinSizeStep: 4
  # minMarkerPerimeterRate: 0.04
  # minMarkerPerimeterRate: 0.01
  maxMarkerPerimeterRate: 4.0
  polygonalApproxAccuracyRate: 0.02
  # minMarkerDistanceRate: 0.5