detect_marker: true
detect_robot: false
show_contour_area: false 
save_robot_detection_images: false
undistort_method: default
initial_x_location: 0.0
initial_y_location: -4.0
target_x_location: 0.0
target_y_location: 450.0
notebook_display: false
save_images: true
debug: 10
print_wheel_values: true

use_custom_detector_parameters: true
detector_parameters:
  adaptiveThreshWinSizeMin: 1
  adaptiveThreshWinSizeMax: 15  # NO
  adaptiveThreshWinSizeStep: 4  # NO
  minMarkerPerimeterRate: 0.01  # NO
  minMarkerLengthRatioOriginalImg: 0.001
  minCornerDistanceRate: 0.02
  maxMarkerPerimeterRate: 4.0
  polygonalApproxAccuracyRate: 0.02
  minMarkerDistanceRate: 0.5  # NO
  errorCorrectionRate: 0.8 
  maxErroneousBitsInBorderRate: 0.4
  markerBorderBits: 2
  aprilTagQuadDecimate: 1.0
  aprilTagQuadSigma: 0.5

max_linear_speed: 1.5
max_angular_speed: 1.0
position_tolerance: 0.1
danger_slow_factor: 0.3
escape_turn_speed: 0.75