detect_marker: true
detect_robot: true
show_contour_area: false 
save_robot_detection_images: true
undistort_method: default
initial_x_location: 0.0
initial_y_location: 0.0
target_x_location: 0.0
target_y_location: 315.0
new_target_x_location: 0.0
new_target_y_location: 330.0
notebook_display: true
save_images: false
debug: 1
print_wheel_values: false
show_live_map: false
resize_factor: 3

use_custom_detector_parameters: false
detector_parameters:
  adaptiveThreshConstant: 4
  adaptiveThreshWinSizeMin: 3
  maxMarkerPerimeterRate: 4.0
  polygonalApproxAccuracyRate: 0.01
  adaptiveThreshWinSizeMax: 25
  minMarkerPerimeterRate: 0.02  # NO
  minCornerDistanceRate: 0.03
  adaptiveThreshConstant: 10
  maxErroneousBitsInBorderRate: 0.15
  errorCorrectionRate: 0.8
  detectInvertedMarker: true
  adaptiveThreshWinSizeMin: 3
    # adaptiveThreshWinSizeMin: 1
    # adaptiveThreshWinSizeMax: 15  # NO
    # adaptiveThreshWinSizeStep: 4  # NO
    # minMarkerLengthRatioOriginalImg: 0.001
    # minCornerDistanceRate: 0.02
    # polygonalApproxAccuracyRate: 0.02
    # minMarkerDistanceRate: 0.5  # NO
    # errorCorrectionRate: 0.8 
    # maxErroneousBitsInBorderRate: 0.4
    # markerBorderBits: 2
    # aprilTagQuadDecimate: 1.0
    # aprilTagQuadSigma: 0.5

max_linear_speed: 1.0
max_angular_speed: 1.0
position_tolerance: 35
danger_slow_factor: 0.033
escape_turn_speed: 0.2
linear_kp: 0.02
angular_kp: 0.05